### ISSUE TITLE
Questions about model training

### ISSUE THREAD

**Issue by kadirnar** [ms-dot-k/TMT#1]
1. Is there any finetuning training support? Or do we have to train from scratch?
2. How many hours did it take in total with 4xA40 GPU?
3. Can I train with different speech models?

**Comment by ms-dot-k** [comment]
Hello @kadirnar,
1. Yes, you can start training from the pre-trained model. To do this, put the pre-trained ckpt at the argument `--checkpoint`
2. It takes about 1 week.
3. Sure you can use any kind of discrete speech token (e.g., EnCodec, etc)
